#<!-- VARIABLES
#PROJECT
#SERVICE
#-->
name: 'Apply changes to SERVICE-infrastructure'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      force-replace:
        description: 'Resource address to force replace during Terraform apply. Example: aws_s3_bucket.example'
        type: string
        required: false
        default: ''
  #push:
  #  branches:
  #    - main
  repository_dispatch:
    types: [remote-trigger]

jobs:
  terraform:
    name: 'Terraform checks & apply'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && inputs.force-replace == ''
        run: |
          echo "tfe_token = \"${{ secrets.TF_API_TOKEN }}\"" >> terraform.auto.tfvars
          terraform apply -auto-approve -input=false

      - name: Terraform Apply with force replace ${{ inputs.force-replace }}
        if: github.ref == 'refs/heads/main' && inputs.force-replace != ''
        run: |
          echo "tfe_token = \"${{ secrets.TF_API_TOKEN }}\"" >> terraform.auto.tfvars
          terraform apply -auto-approve -input=false -replace=${{ inputs.force-replace }}

  notify-discord:
    needs:
      - terraform
    runs-on: ubuntu-latest
    if: secrets.DISCORD_NOTIFY_HOOK_URL != ''
    steps:
      - name: Prepare payload
        run: >-
          (jq -r '.' <<< '
          {
            "username": "PROJECT Bot",
            "content": "SERVICE-infrastructure has been updated"
          }'
          ) > payload

      - name: Send notification
        run: >-
          curl
          --header "Content-Type:application/json"
          --request POST
          --data @payload
          ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
