name: Clone angular template

on:
  create:
  push:

jobs:
  clone-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: codingones/angular-template

      - name: Setup repo, commit and push
        run: |
          rm -rf .git
          git init .
          git config --global user.email "Bot"
          git config --global user.name "bot@bot.bot"
          git add .
          git commit -m "feat: initial commit from template"
          git branch -M main
          git remote add origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push -u origin main --force
