name: Merge Repositories

on:
  workflow_dispatch:

jobs:
  merge_template:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: Checkout template repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          repository: "TEMPLATE_REPOSITORY_1"

      - name: Checkout rebase branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout main
          git remote add template2 https://github.com/TEMPLATE_REPOSITORY_2.git
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch template2
          git rebase -Xours template2/main
          git push origin main --force



#name: Fork template repository
#
#on:
#  push:
#
#jobs:
#  merge_repositories:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout current repository
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#          token: ${{ secrets.PAT }}
#
#      - name: Fork Repository 1
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT }}
#          SOURCE_REPO: "TEMPLATE_REPOSITORY_1"
#        run: |
#          git remote -v
#          git remote add upstream https://github.com/$SOURCE_REPO.git
#          git fetch upstream
#          git branch --set-upstream-to=upstream/main main
#          git remote -v
#        #  gh repo sync ${{ env.github_repository }} -b main --force
#        #git push origin main --force
#
#      - name: Fork Repository 2
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT }}
#          SOURCE_REPO: "TEMPLATE_REPOSITORY_2"
#        run: |
#          git remote -v
#          git remote add upstream https://github.com/$SOURCE_REPO.git
#          git fetch upstream
#          git branch --set-upstream-to=upstream/main main
#          git remote -v
#        #gh repo sync ${{ env.github_repository }} -b main --force
#        #git push origin main --force