name: Rebase on Template Repository and Create Pull Request

on:
  workflow_dispatch:

jobs:
  rebase_on_template:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout rebase branch
        run: |
          git checkout -b rebase-on-template

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add template repository as remote and fetch
        run: |
          git remote add template https://github.com/codingones/angular-template.git
          git fetch template

      - name: Try rebasing on template repository
        run: |
          git rebase -Xtheirs template/squashed

      - name: Success - Push the new branch to the current repository
        run: |
          git push origin rebase-on-template --force

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: Review rebase changes
          body: This pull request contains changes from the rebase on the template repository. Please review them before merging.
          branch: rebase-on-template
          base: main
          labels: rebase,template
